### ISSUE TITLE
bidirectional synchronisation

### ISSUE THREAD

**Issue by mvhulten** [kristapsdz/openrsync#9]
Is it possible (within reasonable bounds) to include support of bi-directional synchronisation, akin to [Unison](http://www.cis.upenn.edu/~bcpierce/unison/)?

**Comment by kristapsdz** [comment]
You mean like rsync remote1:file1 remote1:file2 remote2:dest?  Yes, it can in theory.  The only reason it can't happen is because of connection multiplexing, which basically hobbles the entire protocol.

Specifically, the "server" multiplexes its error log to the client so that the client can show error messages nicely.  If both destination and source were remote, this would be confusing.  So because of multiplexing, we don't get anything nice.

Also, without multiplexing, the protocol could be much faster.  Just sayin'.
